language: python
python:
- '3.6'
install:
- make
- make blast EMAIL=MY_EMAIL PLATFORM="'linux(X64 chip)'"
before_install:
-
after_install:
- pandoc --from=markdown --to=rst --output=README README.md
script:
- make testwithcoverage
after_success:
- coveralls
deploy:
  provider: pypi
  user: jvrana
  password:
    secure: iqfN4Q7LVekxWaLc7bsQvUbIBHzBsGgiYHpHJLzxU5vp9DULeKygI6bVFEaFY3oRWqUzHrXEUeb6WDQhUVj7rxNXuCun1uWe4xYRyYW+lBCJMy5PKozz2yC0AeQyrhcwI6Zd63/9Je5sYHhMcaNL1rbGP9SmuwxzP5UcCY9LexqOJRrYXB6xwOFVES92h9NkAg4OwkYn56H/5rmH0xP64Kx2HQHXP0gW6NxKH83grqN0vq2L2vD67vmB0tnVA4lwpIp+pOGdlTcLPSJIyVP0zp5myTT49uyQKpinis7gGvjoIFN7pDGqNEwDOi/BJ2Z7iPaq+5UlHZIUNFTBThr0EgCq+qDdnRL0oSvQPs7IDy2A5T62kQojKQZ/pw+pCfuD8INm1cmPkGA8s4sGTETE5+mp43eH62ESz37BCk0VkN4HntKyXUwJbEMXydvd0z5JdR4Q/7URPhaVD5akq0+tVujdQtaGYmdMz+foqJrR5gsZrb7q7QeIzNdiPKWTzKUK72oiZtGsnZZm0lJWyvPwcivOI+fDr9WYIgkhfI/h7UtOHfy8BRWwIU6swV5XIa8utZCeltdmV2tMF6qiBKO9p6RWYzKg7/8uNbJQIJnLtIvWgAr0tGMiwglc74i/QWAwpLfCungD2HBD7LKpmQdTin1ZbGQPDygcd0qk+6tFNsc=
  on:
    tags: true
    branch: master
env:
  matrix:
    secure: KDfIDvbkaulgofS/LpdxRFZ4yEsH3fOfbbcwO4F1Eu6RSXoUUlnSvspeYOikxBLJeTzvrSL3go2pmJFqjBt2DLs51ZBtmcE5e3S0svrLQHnMbVE7VdBtHdhhGbvJvH07caspmqaf6W9TnRjz8KFVvjmYNvFomioGmkndQpmZHkW0OA86CO29IbIyaiebVT0v3zFIvxODbfvBicbUmppnbN5W7nJAmtD9oh/aW1tL55cvU2zaeGEp1dPDPSHzoyc1c05bJdJkqwZwx6eXcZDfdn9rTH81lZYUwsg9OF8idsJJyawfW7W8oLToa/nyQ7HnPpPrH/p2+KPnRtk8eazsgzzZamq6VHgTh9X8yGMrgMY/wnBC0MvoWN/wRA1N7tbxgXVotTJzrT4w4Yc9XJ/ICUf9yqpxeN+CpgEf74CnC/IBFr0hX67kGOw0jO/oc6I9VV4H/dJwyl6Y2sZFya0QJwG09nZJSaYSdpVKOsfGLgpx2bXRRRean3YWpUfEwtiSsY5NByipngjqR2EHKVfenpRHqI6l5cE7C5jzGgHiJ5s3pWIhsY7heRrBrp55uyWpGLOdA4aFPBE+hnQ4rt0dq4N2e1fGars1q8EA3uRDiPrL1ZrrhFxTItMBNYkBqW3DSt+bd7Oj23n8ozZjTdHWtn3U8s67G9DD+knye9C1tEI=
